/* UPDATE IMG PATHS HERE
 * To change the image, just change the name, do not change the folder name, thank you.
 */
export const photoPaths = {
  LANDING_IMAGE: "/photos/kbot.webp",
  LANDING_IMAGE_2: "/photos/flagzbot.jpeg",
  WHAT_IS_K_BOT_1: "/photos/aluminium.webp",
  WHAT_IS_K_BOT_2: "/photos/actuators.webp",
  WHAT_IS_K_BOT_3: "/photos/2.webp",
  WHAT_IS_Z_BOT_1: "/photos/isaac_gym.png",
  WHAT_IS_Z_BOT_2: "/photos/zbot1.jpeg",
  WHAT_IS_Z_BOT_3: "/photos/code.png",
  GALLERY_1: "/photos/1.webp",
  GALLERY_2: "/photos/2.webp",
  GALLERY_3: "/photos/3.webp",
  GALLERY_4: "/photos/4.webp",
  GALLERY_5: "/photos/5.webp",
  GALLERY_6: "/photos/6.webp",
  ZBOT_GALLERY_1: "/photos/zbot1.jpeg",
  ZBOT_GALLERY_2: "/photos/zbotgal.jpeg",
  ZBOT_GALLERY_3: "/photos/zbotgal2.jpeg",
  ZBOT_GALLERY_4: "/photos/zbot2.jpeg",
  ZBOT_GALLERY_5: "/photos/zbotgal3.jpeg",
  ZBOT_GALLERY_6: "/photos/zbot.jpeg",
  COMMUNITY_MAIN_BIG: "/photos/C2.webp",
  COMMUNITY_UPPER_RIGHT: "/photos/C3.webp",
  COMMUNITY_BOTTOM: "/photos/C1.webp",
  ZBOT_COMMUNITY_MAIN_BIG: "/photos/community2.jpg",
  ZBOT_COMMUNITY_BOTTOM: "/photos/community1.jpg",
  ZBOT_COMMUNITY_UPPER_RIGHT: "/photos/community3.png",
  ZBOT_TEAM: "/photos/zbotteam.png",
  ZBOT_PARTNERS_SVG_BLACK: "/photos/zbotpartnersblack.svg",
  ZBOT_PARTNERS_SVG_WHITE: "/photos/zbotpartnerswhite.svg",

  NEW_UI_FOR_BG: '/photos/new-ui/for_bg.jpg',
  NEW_UI_HERO_BG: '/photos/new-ui/hero_bg.jpg',
  NEW_UI_SELLING_POINT_1: '/photos/new-ui/selling_point_1.jpg',
  NEW_UI_SELLING_POINT_2: '/photos/new-ui/selling_point_2.jpg',
  NEW_UI_SELLING_POINT_3: '/photos/new-ui/selling_point_3.jpg',
  NEW_UI_SUBSCRIBE: '/photos/new-ui/subscribe-bg.jpg',
  NEW_UI_WHAT_IS_1: '/photos/new-ui/what_is_1.jpg',
  NEW_UI_WHAT_IS_2: '/photos/new-ui/what_is_2.jpg',
  NEW_UI_ZBOT_1: '/photos/new-ui/zbot_1.jpg',
  NEW_UI_ZBOT_2: '/photos/new-ui/zbot_2.jpg',
  NEW_UI_ZBOT_3: '/photos/new-ui/zbot_3.jpg',
};
export const photoPathAltText = {
  LANDING_IMAGE_ALT: "Header",
  LANDING_IMAGE_ALT_2: "Header",
  WHAT_IS_K_BOT_1_ALT: "Photo: Close-up photo of K-Bot's aluminum chassis",
  WHAT_IS_K_BOT_2_ALT: "Photo: Close-up photo of K-Bot's 120 Nm actuators",
  WHAT_IS_K_BOT_3_ALT: "Photo: Close-up photo of K-Bot's onboard Jetson AGX",
  WHAT_IS_Z_BOT_1_ALT: "Photo: Z-Bot's advanced hardware design",
  WHAT_IS_Z_BOT_2_ALT: "Photo: Z-Bot's actuators and sensors",
  WHAT_IS_Z_BOT_3_ALT: "Photo: Z-Bot's software capabilities",
  GALLERY_1_ALT: "Gallery Image 1",
  GALLERY_2_ALT: "Gallery Image 2",
  GALLERY_3_ALT: "Gallery Image 3",
  GALLERY_4_ALT: "Gallery Image 4",
  GALLERY_5_ALT: "Gallery Image 5",
  GALLERY_6_ALT: "Gallery Image 6",
  COMMUNITY_MAIN_BIG_ALT: "Photo: hackathon attendees tinkering with the Z-01",
  COMMUNITY_UPPER_RIGHT_ALT:
    "Photo: Remi and Martino demoing the homunculus glove and the affordable robotic arm",
  COMMUNITY_BOTTOM_ALT:
    "Photo: wide full shot of K-Bot standing with Master of Technical Staff, Ali Kuwajerwala",
  ZBOT_COMMUNITY_MAIN_BIG_ALT: "Photo: Community members working with Zeroth Bot",
  ZBOT_COMMUNITY_BOTTOM_ALT: "Photo: Community members working with Zeroth Bot",
  ZBOT_COMMUNITY_UPPER_RIGHT_ALT: "Photo: Community collaboration",
  ZBOT_TEAM_ALT: "Photo: Zeroth Bot team members",
  ZBOT_PARTNERS_SVG_BLACK_ALT: "Photo: Our partners: k-scale labs and Grand Journey",
  ZBOT_PARTNERS_SVG_WHITE_ALT: "Photo: Our partners: k-scale labs and Grand Journey",

  NEW_UI_FOR_BG: 'ZBot background',
  NEW_UI_HERO_BG: 'Header background',
  NEW_UI_SELLING_POINT_1: 'Selling point 1',
  NEW_UI_SELLING_POINT_2: 'Selling point 2',
  NEW_UI_SELLING_POINT_3: 'Selling point 3',
  NEW_UI_SUBSCRIBE: 'Subscribe',
  NEW_UI_WHAT_IS_1: 'ZBot background',
  NEW_UI_WHAT_IS_2: 'ZBot background',
  NEW_UI_ZBOT_1: 'ZBot photo',
  NEW_UI_ZBOT_2: 'ZBot photo',
  NEW_UI_ZBOT_3: 'ZBot photo',
};
