/* UPDATE IMG PATHS HERE
 * To change the image, just change the name, do not change the folder name, thank you.
 */
export const photoPaths = {
  LANDING_IMAGE: "/photos/kbot.webp",
  LANDING_IMAGE_2: "/photos/flagzbot.jpeg",
  WHAT_IS_K_BOT_1: "/photos/aluminium.webp",
  WHAT_IS_K_BOT_2: "/photos/actuators.webp",
  WHAT_IS_K_BOT_3: "/photos/2.webp",
  WHAT_IS_Z_BOT_1: "/photos/isaac_gym.png",
  WHAT_IS_Z_BOT_2: "/photos/zbot1.jpeg",
  WHAT_IS_Z_BOT_3: "/photos/code.png",
  GALLERY_1: "/photos/1.webp",
  GALLERY_2: "/photos/2.webp",
  GALLERY_3: "/photos/3.webp",
  GALLERY_4: "/photos/4.webp",
  GALLERY_5: "/photos/5.webp",
  GALLERY_6: "/photos/6.webp",
  ZBOT_GALLERY_1: "/photos/zbot1.jpeg",
  ZBOT_GALLERY_2: "/photos/zbotgal.jpeg",
  ZBOT_GALLERY_3: "/photos/zbotgal2.jpeg",
  ZBOT_GALLERY_4: "/photos/zbot2.jpeg",
  ZBOT_GALLERY_5: "/photos/zbotgal3.jpeg",
  ZBOT_GALLERY_6: "/photos/zbot.jpeg",
  COMMUNITY_MAIN_BIG: "/photos/C2.webp",
  COMMUNITY_UPPER_RIGHT: "/photos/C3.webp",
  COMMUNITY_BOTTOM: "/photos/C1.webp",
  ZBOT_COMMUNITY_MAIN_BIG: "/photos/community2.jpg",
  ZBOT_COMMUNITY_BOTTOM: "/photos/community1.jpg",
  ZBOT_COMMUNITY_UPPER_RIGHT: "/photos/community3.png",
  ZBOT_TEAM: "/photos/zbotteam.png",
  ZBOT_PARTNERS_SVG_BLACK: "/photos/zbotpartnersblack.svg",
  ZBOT_PARTNERS_SVG_WHITE: "/photos/zbotpartnerswhite.svg",

  NEW_UI_FOR_BG: "/photos/new-ui/for_bg.jpg",
  NEW_UI_FOR_ICON_1: "/photos/new-ui/for_icon_1.svg",
  NEW_UI_FOR_ICON_2: "/photos/new-ui/for_icon_2.svg",
  NEW_UI_FOR_ICON_3: "/photos/new-ui/for_icon_3.svg",
  NEW_UI_SELLING_POINT_1: "/photos/new-ui/selling_point_1.jpg",
  NEW_UI_SELLING_POINT_2: "/photos/new-ui/selling_point_2.jpg",
  NEW_UI_SELLING_POINT_3: "/photos/new-ui/selling_point_3.jpg",
  NEW_UI_SUBSCRIBE: "/photos/new-ui/subscribe-bg.jpg",
  NEW_UI_WHAT_IS_1: "/photos/new-ui/what_is_1.jpg",
  NEW_UI_WHAT_IS_2: "/photos/new-ui/what_is_2.jpg",
  NEW_UI_ZBOT_1: "/photos/new-ui/zbot_1.jpg",
  NEW_UI_ZBOT_2: "/photos/new-ui/zbot_2.jpg",
  NEW_UI_ZBOT_3: "/photos/new-ui/zbot_3.jpg",

  NEW_UI_HERO_BG_LIGHT: "/photos/new-ui/v2/hero_bg_light.jpg",
  NEW_UI_HERO_BG_DARK: "/photos/new-ui/v2/hero_bg_dark.jpg",

  NEW_UI_ICON_PYTORCH_LIGHT: "/photos/new-ui/v2/icon_pytorch_light.png",
  NEW_UI_ICON_PYTORCH_DARK: "/photos/new-ui/v2/icon_pytorch_dark.png",
  NEW_UI_ICON_ROS_LIGHT: "/photos/new-ui/v2/icon_ros_light.png",
  NEW_UI_ICON_ROS_DARK: "/photos/new-ui/v2/icon_ros_dark.png",
  NEW_UI_ICON_NVIDIA_LIGHT: "/photos/new-ui/v2/icon_nvidia_light.png",
  NEW_UI_ICON_NVIDIA_DARK: "/photos/new-ui/v2/icon_nvidia_dark.png",
  NEW_UI_ICON_PYTHON: "/photos/new-ui/v2/icon_python.png",

  NEW_UI_ROBOT_1_DARK: "/photos/new-ui/v2/pic_robot_1_dark.jpg",
  NEW_UI_ROBOT_1_LIGHT: "/photos/new-ui/v2/pic_robot_1_light.jpg",
  NEW_UI_ROBOT_2_DARK: "/photos/new-ui/v2/pic_robot_2_dark.jpg",
  NEW_UI_ROBOT_2_LIGHT: "/photos/new-ui/v2/pic_robot_2_light.jpg",
  NEW_UI_ROBOT_3_DARK: "/photos/new-ui/v2/pic_robot_3_dark.jpg",
  NEW_UI_ROBOT_3_LIGHT: "/photos/new-ui/v2/pic_robot_3_light.jpg",
  NEW_UI_ROBOT_4_DARK: "/photos/new-ui/v2/pic_robot_4_dark.jpg",
  NEW_UI_ROBOT_4_LIGHT: "/photos/new-ui/v2/pic_robot_4_light.jpg",

  NEW_UI_AI_1: "/photos/new-ui/v2/pic_ai_1.jpg",
  NEW_UI_AI_2: "/photos/new-ui/v2/pic_ai_2.jpg",
  NEW_UI_AI_3: "/photos/new-ui/v2/pic_ai_3.jpg",
  NEW_UI_AI_4: "/photos/new-ui/v2/pic_ai_4.jpg",

  NEW_UI_USER_1: "/photos/new-ui/v2/pic_user_1.jpg",
  NEW_UI_USER_2: "/photos/new-ui/v2/pic_user_2.jpg",
  NEW_UI_USER_3: "/photos/new-ui/v2/pic_user_3.jpg",
  NEW_UI_USER_4: "/photos/new-ui/v2/pic_user_4.jpg",

  NEW_UI_STUDENTS_1: "/photos/new-ui/v2/pic_students_1.jpg",
  NEW_UI_STUDENTS_2: "/photos/new-ui/v2/pic_students_2.jpg",
  NEW_UI_STUDENTS_3: "/photos/new-ui/v2/pic_students_3.jpg",
  NEW_UI_STUDENTS_4: "/photos/new-ui/v2/pic_students_4.jpg",

  FOR_STUDENTS_1: "/photos/zbotgal3.jpeg",
  FOR_STUDENTS_2: "/photos/zbotbeepbop.png",
  FOR_STUDENTS_3: "/photos/landing.webp",

  FOR_EVERYDAY_1: "/photos/new-ui/zbot_3.jpg",
  FOR_EVERYDAY_2: "/photos/zbot1.jpeg",
  FOR_EVERYDAY_3: "/photos/new-ui/v2/pic_ai_1.jpg",
};

export const photoPathAltText = {
  LANDING_IMAGE_ALT: "Header",
  LANDING_IMAGE_ALT_2: "Header",
  WHAT_IS_K_BOT_1_ALT: "Photo: Close-up photo of K-Bot's aluminum chassis",
  WHAT_IS_K_BOT_2_ALT: "Photo: Close-up photo of K-Bot's 120 Nm actuators",
  WHAT_IS_K_BOT_3_ALT: "Photo: Close-up photo of K-Bot's onboard Jetson AGX",
  WHAT_IS_Z_BOT_1_ALT: "Photo: Z-Bot's advanced hardware design",
  WHAT_IS_Z_BOT_2_ALT: "Photo: Z-Bot's actuators and sensors",
  WHAT_IS_Z_BOT_3_ALT: "Photo: Z-Bot's software capabilities",
  GALLERY_1_ALT: "Gallery Image 1",
  GALLERY_2_ALT: "Gallery Image 2",
  GALLERY_3_ALT: "Gallery Image 3",
  GALLERY_4_ALT: "Gallery Image 4",
  GALLERY_5_ALT: "Gallery Image 5",
  GALLERY_6_ALT: "Gallery Image 6",
  COMMUNITY_MAIN_BIG_ALT: "Photo: hackathon attendees tinkering with the Z-01",
  COMMUNITY_UPPER_RIGHT_ALT:
    "Photo: Remi and Martino demoing the homunculus glove and the affordable robotic arm",
  COMMUNITY_BOTTOM_ALT:
    "Photo: wide full shot of K-Bot standing with Master of Technical Staff, Ali Kuwajerwala",
  ZBOT_COMMUNITY_MAIN_BIG_ALT: "Photo: Community members working with Zeroth Bot",
  ZBOT_COMMUNITY_BOTTOM_ALT: "Photo: Community members working with Zeroth Bot",
  ZBOT_COMMUNITY_UPPER_RIGHT_ALT: "Photo: Community collaboration",
  ZBOT_TEAM_ALT: "Photo: Zeroth Bot team members",
  ZBOT_PARTNERS_SVG_BLACK_ALT: "Photo: Our partners: k-scale labs and Grand Journey",
  ZBOT_PARTNERS_SVG_WHITE_ALT: "Photo: Our partners: k-scale labs and Grand Journey",

  NEW_UI_FOR_BG: "ZBot background",
  NEW_UI_HERO_BG: "Header background",
  NEW_UI_SELLING_POINT_1: "Selling point 1",
  NEW_UI_SELLING_POINT_2: "Selling point 2",
  NEW_UI_SELLING_POINT_3: "Selling point 3",
  NEW_UI_SUBSCRIBE: "Subscribe",
  NEW_UI_WHAT_IS_1: "ZBot background",
  NEW_UI_WHAT_IS_2: "ZBot background",
  NEW_UI_ZBOT_1: "ZBot photo",
  NEW_UI_ZBOT_2: "ZBot photo",
  NEW_UI_ZBOT_3: "ZBot photo",
};

export const photoPathCapabilities = {
  LOCO_MANIP: "/photos/capabilities/0_footsteps.svg",
  AI_ENABLED: "/photos/capabilities/1_aiEnabled.svg",
  FLEX_AND_AGILE: "/photos/capabilities/2_flexAndAgile.svg",
  HARDWARE: "/photos/capabilities/3_hardware.svg",
  OPEN_SOURCE: "/photos/capabilities/4_openSource.svg",
  ECOSYSTEM: "/photos/capabilities/5_ecosystem.svg",
};

export const photoPathCapabilitiesAltText = {
  LOCO_MANIP_ALT: "Z-Bot robot in the center of the photo walking with pencil in hand.",
  AI_ENABLED_ALT: "Close up of Z-Bot robot head with conversation bubbles to show the capabilities of communication.",
  FLEX_AND_AGILE_ALT: "Z-Bot robot dancing in a pirouette stance to show the flexibility of the robot.",
  HARDWARE_ALT: "A close up and internal map of the Z-Bot robot's leg to show the hardware that makes up the foot.",
  OPEN_SOURCE_ALT: "Z-Bot robot against a background of connecting lines to different nodes to show the community aspect of building the robot together. ",
  ECOSYSTEM_ALT: "Z-Bot robot head against a black background with the Python, a cloud, and Pytorch logo to show the internal software ecosystem.",
};
